# -*- coding: utf-8 -*-
"""Target Sistemas - Estágio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLlpxF8Q80srOIdyudOPWicc7Ls1DsFO

# Questão 1
"""

indice = 13
soma = 0
k = 0

while k < indice:
  k = k + 1
  soma = soma + k

print(soma)

"""O valor da variável soma será igual 91.

# Questão 2
"""

def fibonacci (n):
  a, b = 0, 1
  while a <= n:
    if a == n:
      return f"O número {n} pertence à sequência de Fibonacci."
    a, b = b, a + b
  return f"O número {n} não pertence à sequência de Fibonacci."

n = int(input("Digite um número: "))
print(fibonacci(n))

"""# Questão 3"""

import json

faturamento_json = '''
{
    "faturamento": [100, 200, 0, 300, 0, 150, 500, 0, 100, 0, 0, 200, 250, 0, 0, 450]
}
'''

dados = json.loads(faturamento_json)
faturamento = dados['faturamento']

faturamento = [dia for dia in faturamento if dia > 0]

menor_valor = min(faturamento)
maior_valor = max(faturamento)
media_mensal = sum(faturamento) / len(faturamento)
dias_acima_media = sum(1 for dia in faturamento if dia > media_mensal)

print(f"Menor valor: {menor_valor}")
print(f"Maior valor: {maior_valor}")
print(f"Dias acima da média: {dias_acima_media}")

"""# Questão 4


"""

faturamento = {
    'SP': 67836.43,
    'RJ': 36678.66,
    'MG': 29229.88,
    'ES': 27165.48,
    'Outros': 19849.53
}

total = sum(faturamento.values())

percentuais = {estado: (valor / total) * 100 for estado, valor in faturamento.items()}

for estado, percentual in percentuais.items():
    print(f"{estado}: {percentual:.2f}%")

"""# Questão 5"""

def inverter_string(s):
    invertida = ""
    for c in s:
        invertida = c + invertida
    return invertida

s = input("Digite um texto para ser invertido: ")
print(inverter_string(s))